#!/bin/bash

# SysUpdate INSTALLER
# This is a bash script used to update Debian and/or Ubuntu based systems.  
# It updates apt, flatpak and snap packages.
# Jun 26, 2020 - Version 0.3.2

printf "\n[ ** ] Copyting Files\n";
cp sysupdate /usr/bin;

printf "[ ** ] Getting Permision\n";
chmod +x /usr/bin/sysupdate;

printf "[ ** ] Setting Icon\n";
cp SysUpdateIcon.png /usr/share/icons/;

printf "[ ** ] Creating Application Shortcut\n";
cp sysupdate.desktop /usr/share/applications/;

# unnessery 
operation() {
    sudo cp sysupdate /usr/bin;
    sudo chmod +x /usr/bin/sysupdate;
    sudo cp SysUpdateIcon.png /usr/share/icons/SysUpdateIcon.png;
    sudo cp sysupdate.desktop /usr/share/applications/sysupdate.desktop;
}

printf "[ ** ] Install Complete\n"; echo && exit 0;
