#!/bin/bash

#This is a bash script used to update Debian and/or Ubuntu based systems.  
#It updates apt, flatpak and snap packages.
#Jun 22, 2020 - Version 0.2


check_exit_status() {
    if [ $? -eq 0 ]
    then
        echo -e "\n===> Success \e[92m√√√√√ \e[0m\n"
        for i in {235..255} {255..235} ; do echo -en "\e[38;5;${i}m==\e[0m" ; done 
        echo
    else
        echo
        echo -e "\e[31m[ERROR]\e[39m Process Failed!"
        echo
        read -p "The last command exited with an error. Exit script? (yes/No) " answer
        if [ "$answer" == "yes" ]
        then
            echo
            echo -e "\e[31mAborting update...\e[0m"
            echo
			echo
            read -p "Press enter to exit..."
            exit 1
        fi
    fi
}

greeting() {
    sudo clear
    echo "Hello $USER,"
    echo -e "\e[1m \e[48;5;235m"
    echo -e "  __                           _       _        "
    echo -e " / _\_   _ ___ /\ /\ _ __   __| | __ _| |_ ___  "
    echo -e " \ \| | | / __/ / \ \ '_ \ / _  |/ _  | __/ _ \ "
    echo -e " _\ \ |_| \__ \ \_/ / |_) | (_| | (_| | ||  __/ "
    echo -e " \__/\__, |___/\___/| .__/ \__,_|\__,_|\__\___| "
    echo -e "     |___/          |_|                         "
    echo -e "                     Jun 22, 2020 - Version 0.2 "
	echo -e "\e[0m\e[48;5;235m              Jorge Costa @ JORGECOSTAtech 2020 "
    echo -e "\e[0m"
    echo "This bash script is used to update Ubuntu based systems."
    echo "It updates apt, flatpak and snap packages."
    echo "Tested and working on Ubuntu 20.04LTS based systems with"
    echo "flatpak and snap enabled."
    echo
    echo "Current kernel version:" && uname -r
    echo
    read -p "Do you want to proceed? (Yes/no) " answer2
    if [ "$answer2" == "no" ]
        then
            echo
            echo -e "\e[31mAborting update...\e[0m"
            echo
			echo
            read -p "Press enter to exit..."
            exit 1
        fi
    echo
}

update() {
    echo -e "\e[96m"
    echo -e " ===> APT package list update "
    echo -e "\e[0m"
    sudo apt update;
    check_exit_status

    echo -e "\e[96m"
    echo -e " ===> APT list of upgradable packages "
    echo -e "\e[0m"
    sudo apt list --upgradable;
    check_exit_status
    
    echo -e "\e[96m"
    echo -e " ===> APT package upgrade "
    echo -e "\e[0m"
    sudo apt upgrade;
    check_exit_status

#    sudo apt-get dist-upgrade;
#    check_exit_status

    echo -e "\e[33m"
    echo -e " ===> Flatpaks installed "
    echo -e "\e[0m"
    flatpak list;
    check_exit_status

    echo -e "\e[33m"
    echo -e " ===> Flatpaks upgrade "
    echo -e "\e[0m"
    flatpak update;
    check_exit_status
    
    echo -e "\e[33m"
    echo -e " ===> Snaps installed "
    echo -e "\e[0m"
    sudo snap list;
    check_exit_status    

    echo -e "\e[33m"
    echo -e " ===> Snaps upgrade "
    echo -e "\e[0m"
    sudo snap refresh;
    check_exit_status
}

housekeeping() {
    echo -e "\e[32m"
    echo -e " ===> Cleaning unnecessary packages "
    echo -e "\e[0m"

    sudo apt autoremove;
    check_exit_status

    sudo apt autoclean;
    check_exit_status

    echo -e "\e[32m"
    echo -e " ===> UpdateDB "
    echo -e "\e[0m"
    sudo updatedb;
    check_exit_status
}

leave() {
    echo -e "\e[92m"
    echo -e " ------------------ "
    echo -e "| Update Complete! |"
    echo -e " ------------------ "
    echo -e "\e[0m"
	echo
    read -p "Press enter to exit..."
    clear
    exit
}

greeting
update
housekeeping
leave
